AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

  Exclude:
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

###############################################
# Disable while old code will not be rewriten #
###############################################

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
