AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

  Exclude:
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
